config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "tasks", to: "tasks#index", as: :tasks
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  delete "tasks/:id", to: "tasks#destroy", as: :delete
  patch "tasks/:id", to: "tasks#update", as: :task
  get "tasks/new", to: "tasks#new", as: :new_task
  get "tasks/:id", to: "tasks#show" ,as: :task_id
  post "tasks", to: "tasks#create"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
     @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    # redirect_to prefix_path
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other

  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed , "Task completed"  %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if(task.completed) %>
        <input type="checkbox" name="completed" checked disabled="true" />
      <% else %>
       <input type="checkbox" name="completed" disabled="true"/>
      <% end %>
      <%=  link_to task.title, task_id_path(task) %>
      <%= link_to "Delete task", delete_path(task),
       data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </li>
 <% end %>
</ul>
<br>
<%= link_to "+ Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed , "Task completed"  %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div>
  <h1 style="text-align:left"> <%= @task.title %></h1>
  <%= link_to "Edit this task",edit_task_path(@task), style: 'text-align:right'%>
</div>
<p><%= @task.details %></p>
<% if(@task.completed) %>
  <input type="checkbox" name="completed" checked  disabled="true"/>
  <label for="completed">This task is completed</label>
<% else %>
  <input type="checkbox" name="completed" disabled="true" />
  <label for="completed">This task is not completed</label>
<% end %>
<br>
<%= link_to "Back to list", tasks_path %>